name: Deploy Next.js App to GitHub Pages

on:
  push:
    branches:
      - main   # main 브랜치에 push 발생 시 빌드 및 배포 실행

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. 코드 체크아웃
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Node.js 설정 (필요한 버전 지정)
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'  # 프로젝트에 맞는 Node.js 버전 사용

      # 3. 의존성 설치
      - name: Install dependencies
        run: npm install

      # 4. Next.js 빌드 (빌드 수행)
      - name: Build Next.js app
        run: npm run build

      # 5. 정적 파일 생성 (next export)
      - name: Export static files
        run: npm run export

      # 6. gh-pages 브랜치로 배포
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./out    # next export 시 생성된 폴더 (기본값: out)
